name: test dispatch

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'version'
        required: true

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: change it
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FILE_TO_COMMIT: d/test.yaml
          DESTINATION_BRANCH: test-5
        run: |
          echo ${{ github.event.inputs.version }}
          export TODAY=$( date -u '+%Y-%m-%d' )
          export MESSAGE="chore: regenerate $FILE_TO_COMMIT for $TODAY"
          export SHA=$( git rev-parse $DESTINATION_BRANCH:$FILE_TO_COMMIT )
          gh api --method PUT /repos/:owner/:repo/contents/$FILE_TO_COMMIT \
            --field message="$MESSAGE" \
            --field content=@<( base64 -i $FILE_TO_COMMIT ) \
            --field branch="$DESTINATION_BRANCH" \
            --field sha="$SHA"
