name: test ulimit

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Check ulimit size
        run: ulimit -a
      - name: change it
        run: ulimit -s 65536
      - name: Check ulimit size 2
        run: ulimit -a 
