# GitHub workflow for createing release.
# Trigger release branch should be merge into main
# TODO add e2e/smoke test for autogen configuration

name: Create Release.

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Release version (Be sure `Release-branch` is successful):"
        required: true

jobs:
  create-release:
    name: Test trigger
    runs-on: ubuntu-latest
    steps:
      - name: Trigger helm post release workflow
        run: |
          curl \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"\
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/Sugar-pack/helm-charts/actions/workflows/post-atlas-operator-release.yaml/dispatches \
            -d '{"ref":"main","inputs":{"version":"'"${{ github.event.inputs.version }}"'"}}'

      
